services:
  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.20.0
    container_name: jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    restart: unless-stopped

  backend1:
    build: .
    container_name: backend1
    env_file: ./.env
    restart: unless-stopped

  backend2:
    build: .
    container_name: backend2
    env_file: ./.env
    restart: unless-stopped

  backend3:
    build: .
    container_name: backend3
    env_file: ./.env
    restart: unless-stopped

  nginx: 
    image: nginx:latest
    container_name: nginx
    ports: ["80:80"]
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
    restart: always